site:
  baseline: Full Stack Software Engineer
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  date:
    format: j F Y
    timezone: Europe/Paris
  paginate:
    max: 5
    path: page
  title: Jeff Conaway
  canonicalurl: true
  description: Blog
  fmpages:
    admin:
      layout: admin/index.html
      title: Content Manager (Netlify CMS)
    redirects:
      layout: _redirects.txt
      permalink: _redirects
  baseurl: /
theme: hyde
